version: '3.9'

services:
  repository:
    build:
      context: .
      dockerfile: dockerfile.db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "SocialNetwork"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: password
    container_name: postgres_db