FROM postgres:14.2-alpine
#COPY ./src/postgres/*.sql /docker-entrypoint-initdb.d/
#RUN chmod a+r /docker-entrypoint-initdb.d/*
#COPY ./src/postgres/postgresql.conf      /tmp/postgresql.conf
#COPY ./src/postgres/updateConfig.sh      /docker-entrypoint-initdb.d/_updateConfig.sh
EXPOSE 5432