spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://localhost:5432/SocialNetwork
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always

  jpa:
#    show-sql: true

  server:
    port: 8189

  spring:
    servlet:
      multipart:
        max-file-size: 15MB
        max-request-size: 15MB